# Substitution variables used through the codebase
substitutions:
  lightbulb:         "\U000F0335"
  ceiling_light:     "\U000F0769"
  lamp:              "\U000F06B5"
  floor_lamp:        "\U000F08DD"
  string_lights:     "\U000F12BA"
  track_light:       "\U000F0914"
  bulkhead_light:    "\U000F1A2F"
  led_strip:         "\U000F07D6"
  coach_lamp:        "\U000F1020"
  ceiling_fan_light: "\U000F1798"
  bed:               "\U000F02E3"
  sunny:             "\U000F05A8"
  spa:               "\U000F0828"
  cat:               "\U000F011B"
  

  icon_font: light40
  text_font: roboto24
  text_color: black
  button_on_color: "ep_orange"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"
  button_height_single: '109px'
  button_height_double: '228px'
  button_width: '150px'
  touchscreen_idle_timeout: "30s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"
  # Boot screen configuration
  boot_screen_delay: 60s

  # Set Night mode  at Mightnight
  screen_night_hour: '0'
  screen_night_minute: '0'

  # Set Day mode at 5:30am
  screen_day_hour: '5'
  screen_day_minute: '30'

  # Screen Size
  screen_height: '480px'
  screen_width: '800px'

esphome:
  name: "waveshare-touch-kitchen"
  friendly_name: "Waveshare7-kitchen"
  comment: "Waveshare 7” ESP32-S3N8R8 Capacitive Touch Display 800×480"

# Time update script - This is run once per second. Use it to update any time related labels.
script:
  - id: time_update
    then:
      - lambda: |-
          // No operation

packages:
  # Generic configuration for ESP32 screens
  # If you need Wi-Fi include this
  wifi: !include modules/base/wifi.yaml
  # Basic ESP 32 stuff
  base: !include modules/base/base.yaml
  # If you have a touch screen include this
  touchscreen: !include modules/base/touchscreen.yaml
  # If your touch screen has a backlight include this
  backlight: !include modules/base/backlignt.yaml
  # All the colors
  colors: !include modules/base/color.yaml
  # Fonts you need
  fonts: !include modules/base/fonts.yaml
  # Your Images
  images: !include modules/base/images.yaml
  # Some basic sensors
  sensors: !include modules/sensors/sensors_base.yaml
  # Styles + Themes
  theme_style: !include modules/base/theme_style.yaml
  # Extra code for pages
  solar: !include modules/solar/sensors_assets_solar.yaml
  #WW sensors added
  #sensors_bark: !include modules/bark_assets/sensors_assets_bark.yaml
  # Harware description file
  hardware: !include modules/hardware/waveshare-esp32-s3-touch-lcd-7.yaml



  # This section will Update button state from Home Assistant
  # Any button that requires real time updates needs a section here


  # Button 2 - Standard light button with state updates
  button_2_state: !include
    file: modules/sensors/switch_or_light_button_state.yaml
    vars:
      uid: button_2
      entity_id: "switch.sonoff_spa_4_channel_filter"
  # Button 4 - Standard light button with state updates including dimming
  button_4_state: !include
    file: modules/sensors/dimmer_light_state.yaml
    vars:
      uid: button_4
      entity_id: light.cat_light

# -------------------------------------------------------------------------
# LVGL pages and buttons
# -------------------------------------------------------------------------
lvgl:
  theme: !include { file: modules/base/theme.yaml }
  page_wrap: true

# Boot screen
  top_layer: !include
    file: modules/screens/boot_screen.yaml
    vars:
      height: $screen_height
      width: $screen_width

# Main Page
  pages:
    - id: main_page
      layout:
        type: flex
        flex_flow: COLUMN_WRAP
      width: 100%
      styles: page_style
      <<: !include
        file: modules/sections/swipe_navigation.yaml
      widgets:
        # Button 2 - Standard light button with state updates
        - button: !include
            file: modules/buttons/switch_button.yaml
            vars:
              uid: button_2
              height: $button_height_single
              text: SPA
              icon: $spa
              entity_id: "switch.sonoff_spa_4_channel_filter"
        # Button 3 - Empty button moves the buttons below it down one
        - button: !include
            file: modules/buttons/transparent_empty_button.yaml
            vars:
              uid: empty_3
              height: $button_height_single
        # Button 4 - Dimming (double hight) light button with state updates
        - button: !include
            file: modules/buttons/dimmer_light_button.yaml
            vars:
              uid: button_4
              height: $button_height_double
              text: Cat Light
              icon: $cat
              entity_id: light.cat_light
        # Temp & Humidity
        #- label:
        #    text_font: $icon_font
        #    text: "-.-°C"
        #    id: temp_kitchen_text
        #    align: bottom_right
        #    text_align: right
        #    text_color: 0xFFFFFF 
        #- label:
        #    text_font: $icon_font
        #    text: "-.- %"
        #    id: humidity_kitchen_text
        #    align: bottom_right
        #    text_align: right
        #    text_color: 0xFFFFFF 
        #- label:
        #    text_font: $icon_font
        #    text: "-.- *"
        #    id: illuminance_kitchen_text
        #    align: bottom_right
        #    text_align: right
        #   text_color: 0xFFFFFF 
        # Solar Page Button

        - button: !include
            file: modules/buttons/page_button.yaml
            vars:
              uid: solar_page
              height: $button_height_single
              text: Solar
              icon: $sunny
              page: enphase_page
#End First Page


#Next Page
    - id: enphase_page
      width: 100% #480px
      bg_color: white
      <<: !include
        file: modules/sections/swipe_navigation.yaml
      widgets:
        - obj:
            width: 480px
            height: 240px
            pad_left: 4
            layout:
              type: grid
              grid_rows: [ fr(1), fr(1) ]
              grid_columns: [ content, content, content, content, content, content, content ]
              pad_column: 4
              pad_row: 5
            widgets:
# Imported            
              - image:
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 0
                  pad_top: 10
                  src: grid_icon
              - obj:
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 1
                  width: 110
                  height: 50
                  layout:
                    type: FLEX
                    flex_flow: ROW_WRAP
                    flex_align_cross: end
                    flex_align_track: center
                    pad_column: 3
                    pad_row: 1
                  widgets:
                    - label:
                        id: daily_imported_watts
                        text_font: ep28
                        text_color: black
                        text: 888.8
                    - label:
                        id: daily_imported_watts_units
                        text_font: ep14
                        text_color: black
                        text: kWh
                        pad_bottom: 2
                    - label:
                        text_font: ep14
                        text_color: black
                        text: Imported
            # Consumed
              - image:
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 2
                  pad_top: 20
                  pad_left: 6
                  pad_right: 6
                  src: arrow_right_gray
              - obj:
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 3
                  width: 120
                  height: 110
                  layout:
                    type: FLEX
                    flex_flow: ROW_WRAP
                    pad_column: 3
                    pad_row: 1
                    flex_align_main: center
                    flex_align_cross: end
                    flex_align_track: center
                  widgets:
                    - image:
                        pad_left: 25
                        pad_right: 25
                        pad_bottom: 4
                        src: house_icon
                    - label:
                        id: daily_consumption_watts
                        text_color: ep_orange
                        text_font: ep28
                        text: 888.8
                    - label:
                        id: daily_consumption_watts_unit
                        text_color: ep_orange
                        text_font: ep14
                        text: kWh
                        pad_bottom: 2
                    - label:
                        text_font: ep14
                        text_color: black
                        text: Consumed
            # Exported
              - image:
                    grid_cell_row_pos: 0
                    grid_cell_column_pos: 4
                    pad_top: 20
                    pad_left: 6
                    pad_right: 6
                    src: arrow_right_gray
              - image:
                    grid_cell_row_pos: 0
                    grid_cell_column_pos: 5
                    pad_top: 10
                    src: grid_icon
              - obj:
                    grid_cell_row_pos: 0
                    grid_cell_column_pos: 6
                    width: 110
                    height: 50
                    layout:
                        type: FLEX
                        flex_flow: ROW_WRAP
                        flex_align_cross: end
                        flex_align_track: center
                        pad_column: 3px
                        pad_row: 1px
                    widgets:
                      - label:
                          id: daily_exported_watts
                          text_font: ep28
                          text_color: black
                          text: 888.8
                      - label:
                          id: daily_exported_watts_unit
                          text_font: ep14
                          text_color: black
                          text: kWh
                          pad_bottom: 2
                      - label:
                          text_font: ep14
                          text_color: black
                          text: Exported                        
         # Produced               
              - image:
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 0
                  pad_top: 10
                  pad_bottom: 2
                  pad_right: 2
                  src: produced_icon
              - obj:
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 1
                  width: 110
                  height: 50
                  layout:
                    type: FLEX
                    flex_flow: ROW_WRAP
                    flex_align_cross: end
                    flex_align_track: center
                    pad_column: 3
                    pad_row: 1
                  widgets:
                    - label:
                        id: daily_solar_production_watts
                        text_font: ep28
                        text_color: ep_blue
                        text: 888.8
                    - label:
                        id: daily_solar_production_watts_label
                        text_font: ep14
                        text_color: ep_blue
                        text: kWh
                        pad_bottom: 2
                    - label:
                        text_font: ep14
                        text_color: black
                        text: Produced
         # Net Imported           
              - obj:
                    grid_cell_row_pos: 1
                    grid_cell_column_pos: 4
                    bg_opa: TRANSP
                    width: 25

              - image:
                    id: daily_net_watts_icon
                    grid_cell_row_pos: 1
                    grid_cell_column_pos: 5
                    pad_top: 10
                    src: up_arrow  

              - obj:
                    grid_cell_row_pos: 1
                    grid_cell_column_pos: 6
                    width: 110
                    height: 50
                    layout:
                        type: FLEX
                        flex_flow: ROW_WRAP
                        flex_align_cross: end
                        flex_align_track: center
                        pad_column: 3
                        pad_row: 1
                    widgets:
                      - label:
                          id: daily_net_watts
                          text_font: ep28
                          text_color: black
                          text: 888.8
                      - label:
                          id: daily_net_watts_units
                          text_font: ep14
                          text_color: black
                          text: kWh
                          pad_bottom: 2
                      - label:
                          text_font: ep14
                          text_color: black
                          text: Net Imported        
      on_click:
        then:
          lvgl.page.show: main_page