---
esphome:
  on_boot:
    priority: -100
    then:
      - delay: $boot_screen_delay
      - lvgl.widget.hide: boot_screen

lvgl:
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  on_idle:     
    timeout: $touchscreen_idle_timeout
    then:
      - logger.log: "LVGL is idle"
      - if:
      # Only turn off screen if night_mode is on
          condition:
            - lambda: |-
                return id(late_night_mode);
          then:
            - light.turn_off: display_backlight
            - lvgl.pause:
                show_snow: true

# Wake on screen touch
touchscreen:
  on_touch:
    then:
      - logger.log: "LVGL is active"
      - lvgl.resume:
      - if:
      # Only turn on baclight and set to 50% if late_night_mode is on
          condition:
            - lambda: |-
                return id(late_night_mode);
          then:
            - light.turn_on:
                id: display_backlight
                brightness: 50%